esphome:
  name: three-speed-fan
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'MYWIFI'
  password: 'opensesame'
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "three-speed-fan"
    password: "ap123456"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: add_a_key_here

ota:
  password: "ota123456"

captive_portal:
    
substitutions: #for the name of the fan to input below
  name: Three Speed Fan

binary_sensor:
  - platform: gpio
    id: push_button
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: true
    name: "Three Speed Fan Cycle"
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - fan.cycle_speed: threespeedfan

switch:
  - platform: gpio
    internal: true
    name: "${name} High Relay"
    pin: GPIO14
    inverted: false
    icon: mdi:fan-speed-3
    id: relay3
    interlock: &interlock_group [relay1, relay2, relay3]
    interlock_wait_time: 300ms
            
  - platform: gpio
    name: "${name} Medium Relay"
    internal: true
    pin: GPIO4
    inverted: false
    icon: mdi:fan-speed-2
    id: relay2
    interlock: *interlock_group
    interlock_wait_time: 300ms
            
  - platform: gpio
    name: "${name} Low Relay"
    internal: false
    pin: GPIO5
    inverted: false
    icon: mdi:fan-speed-1
    id: relay1 
    interlock: *interlock_group
    interlock_wait_time: 300ms

output:
  - platform: template
    id: threespeedfan_1
    type: float 
    write_action:
      - if:
          condition:
            lambda: return ((state == 0));
          then:
            # action for off
            - switch.turn_off: relay1
            - switch.turn_off: relay2
            - switch.turn_off: relay3
      - if:
          condition:
            lambda: return ((state > 0) && (state < 0.4));
          then:
            # action for speed 1
            - switch.turn_off: relay2
            - switch.turn_off: relay3
            - switch.turn_on: relay1
            
      - if:
          condition:
            lambda: return ((state > 0.4) && (state < 0.7));
          then:
            # action for speed 2
            - switch.turn_off: relay1
            - switch.turn_off: relay3
            - switch.turn_on: relay2
            
      - if:
          condition:
            lambda: return ((state > 0.7));
          then:
            # action for speed 3
            - switch.turn_off: relay1
            - switch.turn_off: relay2
            - switch.turn_on: relay3
            
fan:
  - platform: speed
    id: threespeedfan
    output: threespeedfan_1
    name: "Three Speed Fan"
    speed_count: 3